services:
  jupyter:
    image: ghcr.io/astral-sh/uv:debian-slim
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - HTTP_PROXY=http://proxy.omu.ac.jp:8080
      - HTTPS_PROXY=http://proxy.omu.ac.jp:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["2"]
              capabilities: [gpu]
    working_dir: /app
  
  azure:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: azure
    tty: true
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTPS_PROXY}
    volumes:
      - .:/app
    working_dir: "/app"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["2"]
              capabilities: [gpu]
